### ISSUE TITLE
Demo code not working

### ISSUE THREAD

**Issue by mobihunterz** [micnews/html-to-article-json#96]
I have tried to work on demo given here but I was not able to properly run the same.

main.js:
```
var htmlToArticleJson = require('html-to-article-json');
var htmlString = '<p>Foo<b>bar</b></p>';
var articleJson = htmlToArticleJson(htmlString);
//articleJson();

console.log("Article JSON: " + articleJson);
```

If I use `opts` with require, it gives `opts` undefined value because I don't know what should be `opts`, so, I can declare a variabe on this.

when I run this js, I get output as:

```
Article JSON: function (elm) {
    return normalize(parse(elm));
  }
```

Please let me know how to tackle the issue.

**Comment by ellell** [comment]
Hi @mobihunterz, sorry the docs our outdated. The opts are actually optional so you should be able to get this running by changing your require to this: 

``` js
var htmlToArticleJson = require('html-to-article-json')();
```

**Comment by ellell** [comment]
@mobihunterz I removed the optional `opts` from the readme for now, but I'll add some explanation in the readme about what you can do with the opts as soon as I can!
